### ISSUE TITLE
KeyNotFoundException during Android rotation

### ISSUE THREAD

**Issue by tbalcom** [aritchie/userdialogs#165]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
[] iOS
[X] Android
[] UWP
[] PCL

2) Please state the issue to the best of your ability below

I'm using ACR.UserDialogs version 5.1.0 in Xamarin.Android 6.0 using MvvmCross 4.1.4.  If I show an async ActionSheetDialog dialog from a ViewModel then rotate the phone while the dialog is active then the application crashes due to an unhandled exception.

If I add `ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize` to the Activity then it no longer crashes during rotation. I was under the impression the main reason for using DialogFragments was to fix rotation issues on Android?  Issue #138 seems to suggest the library has switched to use DialogFragments to avoid dialogs disappearing during rotation on Android.  Should this be working without the `ConfigurationChanges` ?

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException () [0x00000] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/throwhelper.cs:70 
   at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (System.Collections.Generic.TKey key) [0x00021] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/collections/generic/dictionary.cs:176 
   at Acr.UserDialogs.Fragments.InMemoryConfigStore.Pop[T] (Android.OS.Bundle bundle) [0x0000d] in C:\dev\modules\userdialogs\src\Acr.UserDialogs.Android\Fragments\InMemoryConfigStore.cs:26 
   at Acr.UserDialogs.Fragments.AbstractAppCompatDialogFragment`1[T].OnCreateDialog (Android.OS.Bundle bundle) [0x0000d] in C:\dev\modules\userdialogs\src\Acr.UserDialogs.Android\Fragments\AbstractDialogFragment.cs:25 
   at Android.Support.V4.App.DialogFragment.n_OnCreateDialog_Landroid_os_Bundle_ (IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) [0x00011] in <filename unknown>:0 
   at (wrapper dynamic-method) System.Object:08ecf61e-8092-4fea-b07b-1fe6c260c46e (intptr,intptr,intptr)```

**Comment by aritchie** [comment]
I'm using dialog fragments internally.  I'm not sure if fragments work under rotation without those flags as I've always used them.  If you've added them and it's working, then I considered this a closed case

**Comment by fedotovsi** [comment]
I have the same issue on rotation and I can use this flags(((
Could you please provide a tip to resolve this issue on rotation?

**Comment by aritchie** [comment]
Add the following to your activity attribute - ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize

**Comment by fedotovsi** [comment]
sorry, I miss, I can't use this flags

**Comment by aritchie** [comment]
Well - not much I can say then

**Comment by fedotovsi** [comment]
hm, you have great library!  why did you put any restrictions on it?
I thought, that problem related to MvvmCross, so on every OnCreate-OnDestroy for fragment I have totally new objects for controls, so your AbstractAppCompatDialogFragment is always new object after destroying the fragment, so it seems for resolving this problem it seems not enough to put config id, but it needs to serialize also the config, anyway, this behavior will be not only for rotation, but at any destroyfragment so if user decide to hide the application and system will need some memory, I guess it will crash.
So I decided to run your examples, it was difficult to run it, because my setup won't work with profile259 on Android platform, I changed to profile111 and it works.
So after run an alert with ConfigChanges.ScreenSize | ConfigChanges.Orientation parameters
I get a black screen.
Without these parameters I have:
Java.Lang.IllegalStateException: Fragment does not have a view
05-27 16:46:44.846 E/mono    ( 2945):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3236/ee215fc9/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
05-27 16:46:44.846 E/mono    ( 2945):   at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (IntPtr jobject, IntPtr jclass, IntPtr jmethod) [0x00083] in /Users/builder/data/lanes/3236/ee215fc9/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:1010 
05-27 16:46:44.846 E/mono    ( 2945):   at Android.App.Activity.OnStart () [0x00058] in /Users/builder/data/lanes/3236/ee215fc9/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.App.Activity.cs:4875 
05-27 16:46:44.846 E/mono    ( 2945):   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnStart () [0x00000] in C:\BuildAgent3\work\aad494dc9bc9783\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:246 
05-27 16:46:44.846 E/mono    ( 2945):   at Android.App.Activity.n_OnStart (IntPtr jnienv, IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3236/ee215fc9/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.App.Activity.cs:4859 
05-27 16:46:44.846 E/mono    ( 2945):   at (wrapper dynamic-method) System.Object:9f33997f-b4d0-47ae-9c6c-82f553a77e3c (intptr,intptr)

**Comment by aritchie** [comment]
I didn't put any restrictions on it.  It does not relate to MvvmCross or Xamarin Forms.  They are not a factor.  

You can't serialize the dialog because the callbacks themselves, don't serialize.  This was the only way to keep the backend action hooked up.  If the screen rotated before, the dialogs were just lost and your async method was left to hang.

I have no idea what your exception is caused by.  It isn't the dialog library itself.  The samples themselves, use forms with this configuration attached.

**Comment by fedotovsi** [comment]
I see, thanks for you support

**Comment by fedotovsi** [comment]
I found out that it can be easily fixed,
Can I make the pull request?

**Comment by aritchie** [comment]
Absolutely
