### ISSUE TITLE
HTML Formatted Text to SetMessage

### ISSUE THREAD

**Issue by swathi1111** [aritchie/userdialogs#324]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [*] PCL

## Version of ACR UserDialogs Library

6.3.5

## Expected Behaviour

I wish the user to see a HTML formatted "End User License Agreement" text in the dialog with AGREE/DISAGREE options.

onfirmConfig cc = new ConfirmConfig();
                        cc.SetOkText("Agree");
                        cc.SetCancelText("Disagree");
                        cc.SetTitle("END USER LICENSE AGREEMENT");

                        ISpanned _eula = FromHtml("<b>Please read this End-User License Agreement (“Agreement” or “EULA”) ... </b>");

string message = _eula.ToString();

cc.SetMessage(message);

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

All the text including <b> tags are displayed instead of **BOLD** text.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I'll consider this for a future release.  It is unlikely though due to different platform behaviours.

**Comment by andreipro** [comment]
Hey @aritchie,
Are there any chances that this feature will be implemented soon? 
There are some problems with styling the message text from dialog because the **textAppearanceMedium** property is no longer available since material theme (https://stackoverflow.com/questions/35179537/android-message-font-size-in-alertdialog-through-styles/36749547#36749547). And at this moment I can't set the text style for message to bold or italic. The text style can be set to the title, and I tried to use the text in the title instead, but unfortunately it has a maximum of 2 lines and this can't be changed. 
As you can see in the link above, you can set the text style programatically, but I don't have access to the dialog object when using **UserDialogs.Instance.Confirm()** . If you have solutions for this problem please let me know. Thanks.

**Comment by aritchie** [comment]
I don't have a need for this feature at all.  So unless it's coming from someone else, I have no idea when it will be implemented
