### ISSUE TITLE
How to display a confirm dialog?

### ISSUE THREAD

**Issue by wierzba3** [aritchie/userdialogs#332]
I would like to know how I can prompt a user with a confirm dialog, and specify an action to be taken on delete? I can find no documentation (is there any?).

From what I can find online in code samples this is how to do it:
But ConfirmConfig has no OnConfirm field. Did something change?

                    ConfirmConfig config = new ConfirmConfig()
                    {
                        Message = "Delete this smoke record?",
                        OkText = "Delete",
                        CancelText = "Cancel",
                        OnConfirm = { ...code... }
                    };
                    await UserDialogs.Instance.Confirm(config);

**Comment by aritchie** [comment]
There are no docs.  I don't have the time in life to do them.  Intellisense and sample code are the answers for you.  Although, I'd appreciate PR's in this area!

Don't set OnAction when using the async methods.  The library will intentionally crash out saying not to set them because the async mechanism uses them instead.

Here is what you need for the async version.

```csharp
var result = await UserDialogs.Instance.ConfirmAsync(new ConfirmConfig
{
                    Message = "Delete this smoke record?",
                    OkText = "Delete",
                    CancelText = "Cancel"
});
if (result) 
{
    // do something
}
```

**Comment by aaronclausen** [comment]
Thanks I think this resolve some crashing issues for me. I was previously setting the OnAction event to an async function and I was getting random crashes. Have refactored all my code to follow the above example now..
