### ISSUE TITLE
issue with Android version 25.1.0

### ISSUE THREAD

**Issue by biozal** [aritchie/userdialogs#337]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
Android version 25.1.0

## Version of ACR UserDialogs Library
6.3.7

## Expected Behaviour
be able to upgrade Xamarin nuget packages to 25.1.0 support and have arc user dialogs support the upgrade.  

## Actual Behavior
can't upgrade nuget packages.  Have submitted PR To fix issue.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
seriously - do not request library updates!!  You clearly did not read the code of conduct since it is line 1!  You can submit a PR for the 10 seconds is takes to update, but did you actually run all of the test cases in the samples!?  Major updates to the support libraries tend to break things which I later have to support.
