### ISSUE TITLE
Feature Request: Dialogs with custom content

### ISSUE THREAD

**Issue by hardcodet** [aritchie/userdialogs#368]
### Feature Request (hence not using the template)

This is a nearly complete solution for all my dialog needs - except (I think) for the possibility to quickly show an overlay with some custom content, e.g. a ContentView. If you could consider this for a future version, that would be awesome!

**Comment by aritchie** [comment]
I am working on something for v7 (if I ever get around to finishing it that will allow for slightly more extensibility), but I will never make this library take a custom native view as it defeats the purpose of this library.  I also can't integrate a monster like Xamarin forms because this library is used beyond xamarin forms.

**Comment by hardcodet** [comment]
Fair enough :)
Thanks for the quick reply, and keep up the good work!
