### ISSUE TITLE
ActionSheet not showing in android

### ISSUE THREAD

**Issue by alexrainman** [aritchie/userdialogs#37]
Copy and paste your example but is nor showing anything. No error, no crash but not showing. What i may be missing?

**Comment by alexrainman** [comment]
its related with current instance, do i need to restart userdialogs on each activity?

**Comment by aritchie** [comment]
Check the readme.  If you are using MvvmCross or XamForms, it shows what to do.  If you aren't using either, then you have to supply the top activity in the factory function yourself.

**Comment by alexrainman** [comment]
Not using MvvmCross or Forms. Trying to provide the factory function myself but, do you have some example? If cannot solve it, i have the call init when needed in each activity to make it work. Thanks

**Comment by aritchie** [comment]
You have to manage what the top activity is yourself then.  Since I'm not familiar with your architecture, I have no idea what to tell you beyond that.  You can call Init in ever OnResume, but this does make it a lot more painful to work with.  I may end up changing the signature at some point in the future as well.

You can try using https://github.com/aritchie/droidactivitymon/blob/master/Acr.Android.ActivityMonitor/Monitor.cs   It works with android 4.0.3+, but I will offer zero support if you do use it.

**Comment by alexrainman** [comment]
That works like a charm. I added this to my Application class: RegisterActivityLifecycleCallbacks(new ActivityMonitor()); Thanks
