### ISSUE TITLE
Version 6.3.11 will break Android (Xamarin Forms) Project building

### ISSUE THREAD

**Issue by Li-Yanzhi** [aritchie/userdialogs#373]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
7.1

## Version of ACR UserDialogs Library
6.3.11

Dev Environment:

- Visual Studio 2017 (26403.7)
- Xamarin 4.4.0.34

## Expected Behaviour
When adding userdialogs nuget package to a fresh Xamarin Forms Cross-platform project, then build Android project, it is supposed to be successful with no error.

## Actual Behavior
When Build Android project, it will be failed and here is the exception:
Error: Exception while loading assemblies: **System.IO.FileNotFoundException: Could not load assembly 'Xamarin.Android.Support.Fragment**, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name:“Xamarin.Android.Support.Fragment.dll”
   in Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   in Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   in Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	FarmerApp.Droid	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1399

**Comment by kikolopes90** [comment]
Same here

**Comment by aritchie** [comment]
Ok guys - we need to get one thing straight here - I have no affiliation with xamarin forms, so this issue is not really my problem and it shouldn't be filed here in the future (as stated in the code of conduct that you erased).  

Make sure your project compiler in android is set to "use latest" which should be Android 7.x.  You should also update your support libraries to the latest version.


@kikolopes90 please don't add +1's.  Only additional information is helpful.

**Comment by donbing** [comment]
installing the v25 android sdk and updating the project to compile using 7.1 seems to have fixed this for me.

**Comment by NerijusV** [comment]
This problem still occurs in Android SDK v25 in my environment.
It seems that problem exists with current latest version 6.3.11.
Version 6.3.10 is working correctly.

**Comment by aritchie** [comment]
As per my comment, update your android support libraries to 25.3.1.

**Comment by aritchie** [comment]
The latest nuget forces the update now.  Just update userdialogs and you'll be good now

**Comment by EdHubbell** [comment]
@aritchie - FWIW, I found this ticket to be extremely helpful, as I couldn't figure out what had gone wrong with my Xamarin Forms app until I saw this here. 

I realize that filing what turns out to be a Xamarin Forms problem as an issue with your library (that you put tons of effort into) hijacks your repo's issue list.
