### ISSUE TITLE
"System.TypeLoadException: Could not resolve type with token" using 6.3.11 with Support 24.2.1

### ISSUE THREAD

**Issue by EmilAlipiev** [aritchie/userdialogs#379]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of ACR UserDialogs Library
6.3.11

I downgraded Android Support Libraries from 25.3.1 to 24.2.1 version. So Acr UserDialogs downgraded from 6.4.1 to 6.3.11. But I am getting exception below every time I generate a Toast message. It doesnt occur for Loading message or others. 

Using Support Library 23.3.0 has no problem with 6.3.11 
Using Support Library 25.3.1 has no problem with 6.4.1
Using Support Library 24.2.1 has problem with 6.3.11

First I thought this error is xamarin related(maybe still it is) but I removed, unistalled. reinstalled. deleted bin, obj, temp, cleaned, rebuilt. 
I removed All Acr packages, XF and Android Support packages. Installed again. Nothing helped. Maybe you have any idea? 

```
## 05-16 17:09:56.410 D/Mono    ( 6003): Assembly Ref addref Acr.UserDialogs[0xaa536ce0] -> Xamarin.Android.Support.Design[0xb33f71a0]: 3
Unhandled Exception:

System.TypeLoadException: Could not resolve type with token 01000091
```

**Comment by aritchie** [comment]
I really don't support old versions as there is only one of me.  I upgrade on purpose so I don't have to deal with android support libraries.  6.4.1 will only work with 25.3.1+ which is why it has no problems.  In previous versions, I tried to deal with multiple versions but it simply doesn't work.  Somewhere around v24, something changed internally with the support libraries.

6.3.11 should only be used with 23.3.

**Comment by EmilAlipiev** [comment]
ok thanks for the confirmation. that's what I wanted to hear indeed. Cheers
