### ISSUE TITLE
Acr.UserDialogs 7.0.0-beta1 not compatible with Xamarin.Android.Support.Design >= 26.0.0?

### ISSUE THREAD

**Issue by Szymaniuk** [aritchie/userdialogs#448]
## Expected Behaviour
Acr.UserDialogs 7.0.0-beta1 should work fine with Xamarin.Android.Support.Design >= 26.0.0.

## Actual Behavior
Currently Acr.UserDialogs 6.5.1 works **FINE** with i.e. Xamarin.Android.Support.Design 26.1.0.1.
I was about to update **Acr.UserDialogs** from **6.5.1** to **7.0.0-beta1**, but unfortunately it has dependencies set, that it's working only with **Xamarin.Android.Support.Design** up to 25.x.x version.

Why this dependency has been introduced, as there was no issue at **6.5.1**, with Xamarin.Android.Support.Design **26.1.0.1**?

Thanksa a lot!

**Comment by Szymaniuk** [comment]
Sad, that it has been just *CLOSED* without any comment...
Fortunately, *7.0.0-beta2* supports *Xamarin.Android.Support.Design (>= 26.1.0.1 && < 27.0.0)*, so it's working fine right now.

**Comment by aritchie** [comment]
Here's what's **SAD**

- Instead of saying thank you for answering your complaint, you leave a troll comment
- Your issue was phrased more like I need to explain a decision to you than ask for help, guess what... I don't.
- Your issue violates a simple code of conduct about not asking for external library updates (the part you deleted from the issue template)
- It is a beta.  I am allowed to something for my own testing purposes (shocking)
- You aren't entitled to an answer - I don't work with/for/around you at all.  You don't pay me anything, so don't expect anything.  You get this code for free.
- Your use of **CAPS AND BOLD**

If you behave like a troll/entitled brat in the future, you will simply be banned from filing issues here.
