### ISSUE TITLE
After cancelling existing Confirm dialog with cancellation token, next dialog is not shown on iOS.

### ISSUE THREAD

**Issue by vikram-ma** [aritchie/userdialogs#498]
- [] iOS 

## Version of OS(s) listed above with issue
11.0.3

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
My requirement is to update already shown userdialog, when new notification comes or show new notification dialog
So I tried closing existing dialog programatically and creating new dialog.
1. I programatically close UserDialogs.Instance.ConfirmAsync by sending cancellation token.
2. I call ConfirmAsync again with updated message.

## Actual Behavior
On iOS, previous dialog is closed but new dialog is not shown. When I resend the notification the dialog is shown. i.e 
1. 1st notification is shown, 
2. when 2nd notification comes, 1st is dismissed (expected) but 2nd dialog is not shown
3. when 3rd notification comes, it is shown
4. When 4th notification comes, 3rd is dismissed (expected) but 4th dialog is not shown
and so on.

Observation: On android it worked as expected.

**Comment by aritchie** [comment]
You need to leave a gap in between dialog calls.  iOS takes a second to dismiss the top window due to the animation.  User dialogs uses a hacky mechanism to detect the top window.  Due to the timing, it grabs the window that is in the process of disappearing. 

-> show dialog
-> dismiss, cancel, etc
-> await Task.Delay(250); // roughly
-> show new dialog

**Comment by vikram-ma** [comment]
Thank you for the quick response, I will try this out and let you know! Amazing work on this project btw

**Comment by vikram-ma** [comment]
The solution worked!, thanks. I used 500ms delay, which is working every-time.
