### ISSUE TITLE
Can't install on .Net Standard

### ISSUE THREAD

**Issue by APinheiroPT** [aritchie/userdialogs#522]
I Have started a project with .net standard and i cannot install this library on .net standard project.

Can you help me?

**Comment by aritchie** [comment]
Since you appear to be new to OSS, please note that you need to use the issue template (the one you deleted) when you post here in the future.  Also note, that I don't really do support.  This area is for defects & feature requests.  Lastly, you need to include the errors you see specific to this library when having issues.  I can't really say much without something to work from!

Ensure the ".net standard" project you are installing into is .net standard v2 as I don't support v1.x.

**Comment by aritchie** [comment]
No feedback from user - closing
