### ISSUE TITLE
Acr.UserDialogs 6.5.1 - Login Backspace Issue (Android)

### ISSUE THREAD

**Issue by cvasquez-github** [aritchie/userdialogs#528]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue 
Android 7.0
Xamarin.Android.Support.v4

## Version of ACR UserDialogs Library
Acr.UIserDialogs 6.5.1

## Expected Behaviour
Be able to delete the input using backspace key

## Actual Behavior
Can't use the backspace key on the username or password text inputs.

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by BahramSoheili** [comment]
Hi
I have read your post about SDK 2.0 as you did not have problems with SR300 on R3 2016 in order to background segmentation.
I have involved with a new C# project related to background segmentation with sr300 and with SDK R3 2016 with windows 10 as I could not got to SDK2.0
The segmentation sometimes works but most of the time it could not Init() the SenseManager instance and stuck and getting hang at the starting point.
We are open to switch to any camera and SDK.
I would appreciated if you share your experiences about sr300 segmentation upon SDK R3 2016.
Best regards,
Bahram

**Comment by cvasquez-github** [comment]
Hi Bahram, the Background Segmentation on SR300 is very straightforward with the old SDK, however I noticed similar issues, and found out that were not related to the SDK or code at all, the problem was the COMPUTER. I would recommend to try it in a different system and compare behaviors, with a good Intel based CPU (i7 ideally) and with a good USB 3.0 controller to make it work properly. Have you tried plugging it to a different USB port?
