### ISSUE TITLE
Add support for WPF

### ISSUE THREAD

**Issue by VladislavAntonyuk** [aritchie/userdialogs#534]

**Comment by aritchie** [comment]
Unless it comes in the form of a PR, it is unlikely I will ever implement this

**Comment by VladislavAntonyuk** [comment]
I have implemented some base features, https://github.com/aritchie/userdialogs/pull/536

**Comment by aritchie** [comment]
I do appreciate the PR, but I’m afraid going to have to decline as it doesn’t even implement a fraction of the features for those functions alone.  The problem that comes from things like this is that I get bombed with enhancement requests for a platform I never wanted in the first place.  You can easily push this into your own project since Userdialogs.instance has a setter

**Comment by VladislavAntonyuk** [comment]
The other methods can be implemented later

**Comment by aritchie** [comment]
When they are implemented, I will put it on Nuget and say wpf is supported.

**Comment by VladislavAntonyuk** [comment]
I have update project to build Mac and wpf solution. #544

**Comment by VladislavAntonyuk** [comment]
Why is it closed?

**Comment by aritchie** [comment]
Stale issue with no movement and not something I plan to implement myself
