### ISSUE TITLE
It does not work in Command Method that is created dynamically? 

### ISSUE THREAD

**Issue by mnknedim** [aritchie/userdialogs#566]
- [] Android
 - [] NET Standard 2.0

Xamarin .Forms (v 3.2.0.871581)
Xamarin.Android.Support.v4  (v 27.0.2.1)
Xamarin.Android.Support.v7 (v 27.0.2.1)
Acr.UserDialog (v 7.0.1)

I am creating Command method dynamically. But it had not worked. How can i solve??

private Command TapCommand = new Command((url) =>
{
UserDialogs.Instance.ShowLoading("Bekleyin..", MaskType.Black);
...........
UserDialogs.Instance.HideLoading();
}

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Ahhh I see you’re a repeat offender.  So please quit wasting my time, if you can’t be respectful of filling out a few details then I will simply remove you from being able to post at all

**Comment by mnknedim** [comment]
I understand you, immediately i will fix and againt i will post. You can close this issue :)

**Comment by aritchie** [comment]
Your issue filing isn’t much better.  Use your debugger, check that the code is executing!!  It likely isn’t since Xamarin forms binds to public properties.  Which your command is neither public nor a property.

Listen, you have to do base checks yourself.  The source code is all here for you to review.  OSS doesn’t mean we work for free or to answer support requests like this.
