### ISSUE TITLE
Use different culture

### ISSUE THREAD

**Issue by galadril** [aritchie/userdialogs#568]
I've an app that lets the user choose the language/region. So it can be different then the system settings on your phone. We first use the default culture, until the user settings has been fetched from the api, then we set the one that they've chosen.

is there a way to change the culture for for example the DatePrompt?
At this moment it always takes my system culture

**Comment by aritchie** [comment]
Not through this library for any of the platforms.

**Comment by galadril** [comment]
Dont really get why you close this issue!!

I think that all UI / dialogs should use the CultureInfo.CurrentUICulture to show the correct language/culture on the screen. So for Date/Time picker its a major issue!

**Comment by galadril** [comment]
or CultureInfo.CurrentCulture, also good.. but not just the system culture

**Comment by galadril** [comment]
For iOS, the few lines seems to do the job in a DatePickerRenderer

```
         var date = (UIDatePicker)Control.InputView;
         date.Locale = new NSLocale(CultureInfo.CurrentUICulture.TwoLetterISOLanguageName);
```


    For Android, I didn't find any global answer. The few lines below do not seem to work completely :

```
         Locale locale = new Locale(CultureInfo.CurrentCulture.TwoLetterISOLanguageName);
         Control.TextLocale = locale;
         Resources.Configuration.SetLocale(locale);
```

**Comment by aritchie** [comment]
Ok man - that’s enough.  I answered your question so I closed it.  I feel this isn’t a problem with the library.  I feel it should take the system setting.  The 24 hour hack is something going around for 24 hour clicks so I took it.

As is, if you aren’t happy with this answer.  You are welcome to submit a PR, but I won’t be investing the time to doing this

**Comment by aritchie** [comment]
Also - enough with the entitled attitude here 

* thumbs down on the answer
* opening a 2nd issue because I didn’t answer the first issue you had
* calling this a major issue even though it just isn’t working the way you want it to
* Attacking other parts of the codebase to get your way

I try to make as many features as I can to help people.  I try to support a lot of people too.  I’m a one man show for a ton of libraries and I don’t make a cent doing it, so you can at least be polite!

**Comment by aritchie** [comment]
I appreciate the comments.  You assumed I didn't spend anytime thinking about the request, but I did.  I didn't agree with it (still don't) and you wanted a more in-depth answer which I really can't be bothered to do for every single request anymore.  If you have a disagreement with any OSS maintainer, you can always PR, make your own, find another, etc - but frustration is really not an option.  I was essentially going to remove you from being able to post here.

[iOS Issue] You are correct.  I assumed CultureInfo was being used here as well and was the culprit, but the overarching issue was nothing to do with the library.  It was a config issue with the out-of-box setup with iOS.  

[This isn't a major issue]  It is an enhancement request.  The main objective of this library is to try and give a cross platform to the native controls as they work out of the box for the most part.  CultureInfo is not tied to the native portion at all.  Changing the CultureInfo won't reflect on the native portions of your app anywhere else either.  So... I'm happy to take a PR for this, but this isn't something I feel worth the investment otherwise.

**Comment by galadril** [comment]
Thanks for the explanation, sorry for all.. please don't remove me ;)
