### ISSUE TITLE
[Bug]You must install the nuget package in your main executable/application project

### ISSUE THREAD

**Issue by snehaljadhavgit** [aritchie/userdialogs#633]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] .NET Standard Unit Test
- [] .NET Core Unit Test

## Steps to Reproduce
1.  Execute unit test from ViewModel function
2. That ViewModel function should have UserDialgs.Instance related code

## Expected Behavior
The UserDialgs.Instance line should not give exception while executing from Unit Tests

## Actual Behavior
UserDialgs.Instance line gives exception You must install the nuget package in your main executable/application project

**Comment by aritchie** [comment]
So first off, NO... it shouldn't behave that way.  UserDialogs.Instance operates as the bootloader for the platform.  If you want to run unit tests and you are using statics in your code instead of the IUserDialogs, you should note that UserDialogs.Instance also has a setter.  I would encourage you to take a look at the source code before tossing around "should".

In the future, if you want any hope of getting any help - DO NOT CHANGE THE ISSUE TEMPLATE to suit your needs!  This is not a support channel.  What you see is what you get.
